version: "3.9"
services:
  inventorydev:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
      - "./:/mnt"
    environment:
      INVENTORY_APP_MONGO_URI: mongodb://devinventory:devinventory@mongo/devinventory
    ports:
      - "1234:1234"
      - "33935:33935"
      - "8000:8000"
